# AUTO-GENERATED by tools/generate.py. Do not edit.
from dataclasses import dataclass
from typing import Optional, Any

@dataclass
class Machine:
    _client: Any = None
    machine_id: Optional[str] = None
    name: Optional[str] = None
    status: Optional[str] = None
    production_line: Optional[str] = None
    _id: Optional[str] = None
    def linked(self, link_name: str):
        return self._client.traverse(self, link_name) if self._client else []
    def batches(self):
        return self.linked('batches')
    def quality_findings(self):
        return self.linked('quality_findings')
    def maintenance_actions(self):
        return self.linked('maintenance_actions')
    def documents(self):
        return self.linked('documents')

@dataclass
class Part:
    _client: Any = None
    part_id: Optional[str] = None
    name: Optional[str] = None
    revision: Optional[str] = None
    _id: Optional[str] = None
    def linked(self, link_name: str):
        return self._client.traverse(self, link_name) if self._client else []
    def quality_findings(self):
        return self.linked('quality_findings')

@dataclass
class Order:
    _client: Any = None
    order_id: Optional[str] = None
    product: Optional[str] = None
    status: Optional[str] = None
    _id: Optional[str] = None
    def linked(self, link_name: str):
        return self._client.traverse(self, link_name) if self._client else []
    def batches(self):
        return self.linked('batches')

@dataclass
class Batch:
    _client: Any = None
    batch_id: Optional[str] = None
    machine_id: Optional[str] = None
    order_id: Optional[str] = None
    product: Optional[str] = None
    started_at: Optional[str] = None
    _id: Optional[str] = None
    def linked(self, link_name: str):
        return self._client.traverse(self, link_name) if self._client else []
    def runs_on(self):
        return self.linked('runs_on')
    def belongs_to(self):
        return self.linked('belongs_to')
    def quality_findings(self):
        return self.linked('quality_findings')
    def documents(self):
        return self.linked('documents')

@dataclass
class QualityFinding:
    _client: Any = None
    finding_id: Optional[str] = None
    batch_id: Optional[str] = None
    part_id: Optional[str] = None
    machine_id: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    severity: Optional[str] = None
    status: Optional[str] = None
    timestamp: Optional[str] = None
    _id: Optional[str] = None
    def linked(self, link_name: str):
        return self._client.traverse(self, link_name) if self._client else []
    def reported_for(self):
        return self.linked('reported_for')
    def affects(self):
        return self.linked('affects')
    def finding_machine(self):
        return self.linked('finding_machine')

@dataclass
class MaintenanceAction:
    _client: Any = None
    maintenance_id: Optional[str] = None
    machine_id: Optional[str] = None
    action_type: Optional[str] = None
    description: Optional[str] = None
    timestamp: Optional[str] = None
    _id: Optional[str] = None
    def linked(self, link_name: str):
        return self._client.traverse(self, link_name) if self._client else []
    def performed_on(self):
        return self.linked('performed_on')

@dataclass
class EngineeringDocument:
    _client: Any = None
    document_id: Optional[str] = None
    title: Optional[str] = None
    text: Optional[str] = None
    machine_id: Optional[str] = None
    batch_id: Optional[str] = None
    part_id: Optional[str] = None
    source_system: Optional[str] = None
    dq_score: Optional[float] = None
    valid: Optional[bool] = None
    _id: Optional[str] = None
    def linked(self, link_name: str):
        return self._client.traverse(self, link_name) if self._client else []
    def documents_batch(self):
        return self.linked('documents_batch')
    def documents_machine(self):
        return self.linked('documents_machine')

