from pathlib import Path
import json, re
import yaml
#this is AI generated
ROOT = Path(__file__).resolve().parents[1]
ONTOLOGY_PATH = ROOT / "ontology" / "ontology.yaml"
out_api = ROOT / "api" / "generated_types.py"
out_models = ROOT / "sdk" / "ontoflow_sdk" / "generated_models.py"
out_manifest = ROOT / "api" / "generated_manifest.json"
out_mapping = ROOT / "es" / "ontology_objects.json"
out_docs = ROOT / "es" / "documents.json"

TYPE_MAP = {"string":"str", "enum":"str", "datetime":"str", "float":"float", "boolean":"bool", "integer":"int"}
ES_MAP = {"string":"text", "enum":"keyword", "datetime":"date", "float":"float", "boolean":"boolean", "integer":"integer"}

def snake(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()

def load():
    with open(ONTOLOGY_PATH, encoding="utf-8") as f:
        return yaml.safe_load(f)

def py_type(spec):
    return TYPE_MAP.get(spec.get("type", "string"), "str")

def generate_models(o):
    lines = ["# AUTO-GENERATED by tools/generate.py. Do not edit.\n", "from dataclasses import dataclass\n", "from typing import Optional, Any\n\n"]
    for name, obj in o["objects"].items():
        lines.append("@dataclass\nclass %s:\n" % name)
        lines.append("    _client: Any = None\n")
        for p, spec in obj["properties"].items():
            lines.append(f"    {p}: Optional[{py_type(spec)}] = None\n")
        lines.append("    _id: Optional[str] = None\n")
        lines.append("    def linked(self, link_name: str):\n        return self._client.traverse(self, link_name) if self._client else []\n")
        for lname, link in o.get("links", {}).items():
            if link["from"] == name:
                lines.append(f"    def {lname}(self):\n        return self.linked('{lname}')\n")
            if link["to"] == name and link.get("reverse_name"):
                rn = link["reverse_name"]
                lines.append(f"    def {rn}(self):\n        return self.linked('{rn}')\n")
        lines.append("\n")
    out_models.write_text(''.join(lines), encoding='utf-8')

def generate_types(o):
    lines = ["# AUTO-GENERATED by tools/generate.py. Do not edit.\n", "import strawberry\n", "from typing import Optional\n\n"]
    for name, obj in o["objects"].items():
        lines.append("@strawberry.type\nclass %s:\n" % name)
        lines.append("    id: str\n")
        for p, spec in obj["properties"].items():
            t=py_type(spec)
            lines.append(f"    {p}: Optional[{t}] = None\n")
        lines.append("\n")
    out_api.write_text(''.join(lines), encoding='utf-8')

def prop_mapping(spec):
    typ=spec.get("type", "string")
    if typ == "string":
        if spec.get("keyword") and not spec.get("searchable"):
            return {"type":"keyword"}
        if spec.get("searchable"):
            return {"type":"text", "fields":{"keyword":{"type":"keyword", "ignore_above":256}}}
    return {"type": ES_MAP.get(typ, "keyword")}

def generate_mappings(o):
    common={"object_type":{"type":"keyword"},"dq_score":{"type":"float"},"valid":{"type":"boolean"},"source_system":{"type":"keyword"},"source_hash":{"type":"keyword"},"ingested_at":{"type":"date"},"updated_at":{"type":"date"}}
    props=dict(common)
    docs=dict(common)
    for name,obj in o["objects"].items():
        target=docs if obj.get("index")=="documents" else props
        for p,spec in obj["properties"].items():
            target.setdefault(p, prop_mapping(spec))
    docs["embedding"]={"type":"dense_vector","dims":384,"index":True,"similarity":"cosine"}
    out_mapping.write_text(json.dumps({"mappings":{"dynamic":"strict","properties":props}},indent=2),encoding='utf-8')
    out_docs.write_text(json.dumps({"mappings":{"dynamic":"strict","properties":docs}},indent=2),encoding='utf-8')

def generate_manifest(o):
    manifest={"version":o.get("version"),"objects":{},"links":o.get("links",{}),"actions":o.get("actions",{}),"constraints":o.get("constraints",{})}
    for n,obj in o["objects"].items():
        manifest["objects"][n]={"primary_key":obj["primary_key"],"index":obj["index"],"properties":obj["properties"],"searchable":obj.get("searchable",[])}
    out_manifest.write_text(json.dumps(manifest,indent=2),encoding='utf-8')

if __name__ == "__main__":
    o=load(); generate_models(o); generate_types(o); generate_mappings(o); generate_manifest(o)
    print("Generated GraphQL models, SDK models, ES mappings and ontology manifest.")
