# AUTO-GENERATED by tools/generate.py. Do not edit.
import strawberry
from typing import Optional

@strawberry.type
class Machine:
    id: str
    machine_id: Optional[str] = None
    name: Optional[str] = None
    status: Optional[str] = None
    production_line: Optional[str] = None

@strawberry.type
class Part:
    id: str
    part_id: Optional[str] = None
    name: Optional[str] = None
    revision: Optional[str] = None

@strawberry.type
class Order:
    id: str
    order_id: Optional[str] = None
    product: Optional[str] = None
    status: Optional[str] = None

@strawberry.type
class Batch:
    id: str
    batch_id: Optional[str] = None
    machine_id: Optional[str] = None
    order_id: Optional[str] = None
    product: Optional[str] = None
    started_at: Optional[str] = None

@strawberry.type
class QualityFinding:
    id: str
    finding_id: Optional[str] = None
    batch_id: Optional[str] = None
    part_id: Optional[str] = None
    machine_id: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    severity: Optional[str] = None
    status: Optional[str] = None
    timestamp: Optional[str] = None

@strawberry.type
class MaintenanceAction:
    id: str
    maintenance_id: Optional[str] = None
    machine_id: Optional[str] = None
    action_type: Optional[str] = None
    description: Optional[str] = None
    timestamp: Optional[str] = None

@strawberry.type
class EngineeringDocument:
    id: str
    document_id: Optional[str] = None
    title: Optional[str] = None
    text: Optional[str] = None
    machine_id: Optional[str] = None
    batch_id: Optional[str] = None
    part_id: Optional[str] = None
    source_system: Optional[str] = None
    dq_score: Optional[float] = None
    valid: Optional[bool] = None

